name: keelung
version: 0.8.3.0
github: "btq-ag/keelung"
license: BSD3
author: " BTQ AG"
maintainer: "ty.lai@btq.li"
copyright: "2023 BTQ AG"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/btq-ag/keelung#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - cereal
  - containers
  - deepseq
  - directory
  - galois-field
  - groups
  - mtl
  - process
  - random
  - semirings
  - QuickCheck
  - vector
  - wl-pprint-text

library:
  source-dirs: src

  # other-modules:
  #   - Keelung.Data.BinRep

default-extensions:
  - ImportQualifiedPost

ghc-options:
  - -Wall
  - -Werror=incomplete-patterns
  - -fno-warn-orphans

executables:
  tutorial:
    main: Main.hs
    source-dirs:
      - examples/
    dependencies:
      - keelung

    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror=incomplete-patterns
      - -fno-warn-orphans
